In [2]:
import torch
torch.__version__

'2.10.0+cpu'

In [3]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
tmp = torch.rand(size=(2, 3))
tmp.shape, tmp.dtype, tmp.device

(torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [5]:
tmp = torch.tensor([1, 3, 5])
torch.matmul(torch.rand(size=(2, 3)), torch.rand(size=(3, 4)))

tensor([[0.7175, 0.6517, 0.9449, 1.1882],
        [0.3442, 0.3049, 0.8466, 1.0237]])

In [6]:
torch.manual_seed(111)

linear = torch.nn.Linear(in_features=3,
                         out_features=6)

x = torch.rand((2, 3))
y = linear(x)
print(y)

tensor([[ 0.0906,  0.0058,  0.5342,  0.3171,  0.6458, -0.9599],
        [-0.1214,  0.1426,  0.3497,  0.2289,  0.5455, -0.6826]],
       grad_fn=<AddmmBackward0>)


In [7]:
x = torch.arange(0, 100, 10)
x.max(), x.min(), torch.mean(x.type(torch.float32)), x.sum(), x.argmin()

(tensor(90), tensor(0), tensor(45.), tensor(450), tensor(0))

In [8]:
x = torch.arange(1, 10, 1)
print(x.shape)

print(x.reshape(1, 9).shape)

print(x.view(3, 3).shape)

y = x.reshape(1, 3, 3)

y, y[:, 0]

torch.Size([9])
torch.Size([1, 9])
torch.Size([3, 3])


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([[1, 2, 3]]))

In [9]:
torch.manual_seed(0)
x = torch.rand((7, 7))
y = torch.rand((1, 7))

z = x @ y.T
print(z)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [10]:
z.max(), z.min(), z.argmax(), z.argmin()

(tensor(3.0481), tensor(1.7067), tensor(3), tensor(4))